POST http://localhost:3000/user
Content-Type: application/json

{
  "username": "test1234",
  "password": "testPassw0rd"
}

###


POST http://localhost:3000/test
Content-Type: application/json

{
  "username": "xe7ziuj",
  "password": "testPassw0rd"
}

###


GET http://localhost:3000/user/12
Content-Type: application/json


###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "xe7ziuj",
  "password": "testPassw0rd"
}


###
POST http://localhost:3000/comment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjI4LCJ1c2VybmFtZSI6InhlN3ppdWoiLCJyb2xlIjoiVXNlciIsInByb2ZpbGVQaWN0dXJlIjpbXX0.pKiavnvOu4jLYKRIyuUbSXUh_PfXil4Bj1icu77YFnQ

{
  "jwt": "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjI4LCJ1c2VybmFtZSI6InhlN3ppdWoiLCJyb2xlIjoiVXNlciIsInByb2ZpbGVQaWN0dXJlIjpbXX0.pKiavnvOu4jLYKRIyuUbSXUh_PfXil4Bj1icu77YFnQ",
  "text": "data.text",
  "userId": 1,
  "imageId": 1
}